### PR TITLE
LCA using binary lifting

### LINKED ISSUE #21: Add code for LCA using binary lifting
### Description
Following the contributing guidelines, add the code for LCA using Binary Lifting

### PR DESCRIPTION
**Pull request by ankiiitraj**
Closes #21 
#### Checklist

- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] My code gave a clean output on debugging. (NO warnings/errors)

### CODE REVIEW

**Review by Ritik-7 — COMMENTED** [review]
some comments might be useful for better understanding.

**Comment by anktrj** [comment]
> some comments might be useful for better understanding.

@Ritik-7 Can you mark where should I add more comments? Thanks

**Comment by sanskarseth** [comment]
you can add before every function that what is it doing .

**Comment by anktrj** [comment]
@Vishal19111999 Review this one!

**Comment by anktrj** [comment]
> you can add before every function that what is it doing .

adding thanks for the suggestion!

**Review by sanskarseth — APPROVED** [review]

**Pull request merged**
