### PR TITLE
Added code for finding nth Fibonacci number

### LINKED ISSUE #51: Add code for finding nth fibbonaci number
### FIBBONACI
Add a code for finding the nth fibbonaci number.

### PR DESCRIPTION
**Pull request by YourAKShaw**
### closes #51 
<Do NOT delete this template>
Description: Added code for finding nth Fibonacci number.

#### Checklist
<Put an x between square brackets wherever appropriate>
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] My code gave a clean output on debugging. (NO warnings/errors)

### CODE REVIEW

**Review by ankiiitraj — APPROVED** [review]

**Review by sanskarseth — APPROVED** [review]

**Comment by Ritik-7** [comment]
takes o(n) time . can be optimised.

**Comment by anktrj** [comment]
Yup @Ritik-7  Can be optimized using Matrix Exponentiation!

**Comment by YourAKShaw** [comment]
Should I optimize the code using matrix exponentiation and make the necessary changes?

**Comment by anktrj** [comment]
Yup you can go ahead!

**Comment by YourAKShaw** [comment]
Cool! On it!!

**Comment by Ritik-7** [comment]
changes are always welcome :)

**Comment by YourAKShaw** [comment]
I found a cool article: [Binet's Formula for the nth Fibonacci number](http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html#section1)

This will get the job done in O(1) time. Should I integrate this instead, or should I add both the codes, one with matrix exponentiation with O(logN) complexity and this one?

**Comment by sanskarseth** [comment]
O(1) solution is already merged #51 so don't need to do that again.

**Comment by YourAKShaw** [comment]
Ok, cool, I'll do the matrix exponentiation instead.

**Review by shaurysrivastav27 — APPROVED** [review]

**Comment by sanskarseth** [comment]
yes go fo it...

**Review by ankiiitraj — APPROVED** [review]

**Pull request merged**
