### PR TITLE
added code for level order tree traversal

### LINKED ISSUE #117: Code for level order tree traversal
### Description

self raised addition for the dictionary

### PR DESCRIPTION
**Pull request by Sigsev-Dev**
Closes #117 
<Do NOT delete this template>
Description: <Remove this line and provide a description. The title should be short and relevant.>

#### Checklist
<Put an x between square brackets wherever appropriate without any spaces like [x]>

- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] My code gave a clean output on debugging. (NO warnings/errors)

### CODE REVIEW

**Comment by sanskarseth** [comment]
Input should be taken from the user and not as you have taken as it will not help in CP anyway.
The rest is good to go.

**Review by ankiiitraj — APPROVED** [review]
LGTM

**Review by Ritik-7 — COMMENTED** [review]
convert it into user input and rest seems fine.

**Comment by vishalvibes** [comment]
@Ritik-7 @sanskarseth in what format will input be taken? as it is a binary tree? generally, a pointer is passed in such problems.

**Comment by sanskarseth** [comment]
@Vishal19111999 I was thinking of an arbitrary input in which connection between nodes are given like adjacency list or edge list or any other form. Actually, in this code, everything is hand-written like from node value to taking children as the left child or the right child.
But yes pointer is passed in such problems.
So I am approving this.

**Pull request merged**
