### PR TITLE
Segmented Sieve & Juggler Algorithm added

### LINKED ISSUE #129: Absence of optimal number theory algorithms
While i was analyzing the code-base ,I saw a shortage of optimal number theory algorithms which are very useful in nature & are repeatedly used during competitive programming.  

 While Sieve of Eratosthenes was present Sieve of Sundaram,segmented sieve were missing.Similarly various algos like Pollard's algo and Fermat's algo,(etc.) which are used for faster analysis of prime numbers were also missing.

Also the present condition of code-base is very messy ,so i propose that we segregate the code-base into major heading like ,"Number Theory Algorithms","Graph Algorithms" ,"Dynamic Programming"(etc.),and further divide it into various major subheadings in order to make it easier to navigate.

### PR DESCRIPTION
**Pull request by ghost**
Closes #129 
<Do NOT delete this template>
I have added Segmented Sieve ,which is an extended version of Sieve of Eratosthenes.While sieve of Eratosthenes has O(nloglogn) time complexity,Segmented Sieve has O(sqrt(n)+s). Segmented Sieve is used for for finding the prime numbers in the most optimal way possible.

Apart from this i have also added Juggler's Algorithm which is used for array rotation with O(n) time complexity which is a major improvement over classical 2 nested loop approach.
#### Checklist
<Put an x between square brackets wherever appropriate without any spaces like [x]>

- [x ] I've followed the Contributing guidelines provided in the repository.
- [ x] I've made the changes which were demanded in the linked issue.
- [ x] My code gave a clean output on debugging. (NO warnings/errors)

### CODE REVIEW

**Comment by anktrj** [comment]
Looks like you have created branches form other branches and not from the master.
Nonetheless, keep an eye for conflict resolutions if any rises!
LGTM

**Comment by ghost** [comment]
I was facing an issue with my previous branch so i created an new branch ,is it causing any issue while merging?@akitiiitraj

**Review by prskid1000 — APPROVED** [review]

**Review by sanskarseth — APPROVED** [review]

**Comment by anktrj** [comment]
Merging this will solve several issues, Kindly update the description and this is good to go!

**Comment by ghost** [comment]
Changes have been made to the description.

**Review by prskid1000 — APPROVED** [review]

**Pull request merged**
