### PR TITLE
MultiSource BFS

### LINKED ISSUE #161: Add code for multi source BFS
### Description

<Remove this line> The title should be short and relevant.

### PR DESCRIPTION
**Pull request by rahulmishra11**
Closes #161
<Do NOT delete this template>
Description: Multi Source BFS Algorithm

**Checklist**
<Put an x between square brackets wherever appropriate without any spaces like [x]>

- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] My code gave a clean output on debugging. (NO warnings/errors)

### CODE REVIEW

**Review by rahulmishra11 — COMMENTED** [review]
Implemented Multi Source BFS. Please review it.

**Comment by sanskarseth** [comment]
Please remove < > from your issue number so that the PR will be linked to that particular issue.

**Comment by rahulmishra11** [comment]
> Please remove < > from your issue number so that the PR will be linked to that particular issue.

Done !

**Review by ankiiitraj — APPROVED** [review]
LGTM

**Pull request merged**
